@startuml

title __CONTROLER's Class Diagram__\n

  namespace controler {
    class controler.ControleurPrincipal {
        {static} - idAvantPosteCourant : int
        {static} - instance : ControleurPrincipal
        + ControleurPrincipal()
        + activerVues()
        {static} + getInstance()
        + notifierAjouterAvantPoste()
        + notifierAjouterMine()
        + notifierAmeliorerGouverneur()
        + notifierAmeliorerMine()
        + notifierDebloquerGouverneur()
        + notifierDetruireAvantPoste()
        + notifierDetruireMine()
        + notifierNaviguerAfficherAvPoste()
        + notifierNaviguerAffichergouverneur()
        + notifierNaviguerAjouterAvPoste()
        + notifierNaviguerAjouterMine()
        + notifierNaviguerMenuCulture()
        + notifierNaviguerMenuGouverneurs()
        + notifierNaviguerMenuPopulation()
        + notifierNaviguerMenuPrincipal()
        + notifierNaviguerMenuRecherche()
        + notifierNaviguerMenuSatellites()
        + notifierNaviguerMenuStatistiques()
        + notifierTrierParDebloqueListeGouverneur()
        + notifierTrierParNomListeGouverneur()
    }
  }
  

  controler.ControleurPrincipal o-- vue.NavigateurDesVues : navigateur
  controler.ControleurPrincipal o-- modele.Planete : planete
  controler.ControleurPrincipal o-- vue.VueAjouterAvantPoste : vueAjouterAvantPoste
  controler.ControleurPrincipal o-- vue.VueAjouterMine : vueAjouterMine
  controler.ControleurPrincipal o-- vue.VueAvantPoste : vueAvantPoste
  controler.ControleurPrincipal o-- vue.VueGouverneur : vueGouverneur
  controler.ControleurPrincipal o-- vue.VueMenuCulture : vueMenuCulture
  controler.ControleurPrincipal o-- vue.VueMenuGouverneurs : vueMenuGouverneurs
  controler.ControleurPrincipal o-- vue.VueMenuPopulation : vueMenuPopulation
  controler.ControleurPrincipal o-- vue.VueMenuPrincipal : vueMenuPrincipal
  controler.ControleurPrincipal o-- vue.VueMenuRecherche : vueMenuRecherche
  controler.ControleurPrincipal o-- vue.VueMenuSatellites : vueMenuSatellites
  controler.ControleurPrincipal o-- vue.VueMenuStatistiques : vueMenuStatistiques


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
